# Site settings
title: Curly
email: culy_lin@foxmail.com
description: 😄
baseurl: ""
url: "http://ccurly.github.io"

author:
  name     : Curly Lin
  email    : culy_lin@foxmail.com
  url      : http://ccurly.github.io

github: https://github.com/CCurly
disqus_shortname: "Curly"
google_analytics: UA-52446115-1

paginate: 3
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
